/// KelpyShark Package Installer
///
/// Installs packages from the registry into the project's `libs/` directory.
/// Generates a `kelpy.lock` file to pin resolved versions.

use std::path::Path;
use std::fs;

use crate::manifest;
use crate::registry::Registry;
use crate::resolver;

/// Install all dependencies listed in the project's kelpy.toml.
/// Copies them from the registry into the project's `libs/` directory.
pub fn install_all(project_dir: &Path, registry: &Registry) -> Result<Vec<String>, String> {
    let toml_path = project_dir.join("kelpy.toml");
    let manifest = manifest::load(&toml_path)?;

    let resolved = resolver::resolve(&manifest.dependencies, registry)?;

    let libs_dir = project_dir.join("libs");
    fs::create_dir_all(&libs_dir)
        .map_err(|e| format!("Could not create libs/: {}", e))?;

    let mut installed = Vec::new();

    for dep in &resolved {
        let dest = libs_dir.join(&dep.name);

        if dest.exists() {
            // Already installed — skip
            installed.push(format!("{}@{} (already installed)", dep.name, dep.version));
            continue;
        }

        let src = registry.package_path(&dep.name, &dep.version);
        if !src.exists() {
            return Err(format!(
                "Package '{}@{}' not found in registry. Have you published it?",
                dep.name, dep.version
            ));
        }

        copy_dir_recursive(&src, &dest)?;
        installed.push(format!("{}@{}", dep.name, dep.version));
    }

    // Write lock file
    write_lock_file(project_dir, &resolved)?;

    Ok(installed)
}

/// Install a single named package (for `kelpy install <package>`).
pub fn install_one(
    project_dir: &Path,
    package_name: &str,
    registry: &Registry,
) -> Result<String, String> {
    // Find latest version in registry
    let packages = registry.list_packages()?;
    let versions = packages.get(package_name).ok_or_else(|| {
        format!("Package '{}' not found in registry", package_name)
    })?;

    if versions.is_empty() {
        return Err(format!("Package '{}' has no versions", package_name));
    }

    let latest = versions.last().unwrap();

    // Copy to libs/
    let libs_dir = project_dir.join("libs");
    fs::create_dir_all(&libs_dir)
        .map_err(|e| format!("Could not create libs/: {}", e))?;

    let dest = libs_dir.join(package_name);
    if dest.exists() {
        return Err(format!("Package '{}' is already installed", package_name));
    }

    let src = registry.package_path(package_name, latest);
    copy_dir_recursive(&src, &dest)?;

    // Add to kelpy.toml
    let toml_path = project_dir.join("kelpy.toml");
    if toml_path.exists() {
        let mut manifest = manifest::load(&toml_path)?;
        manifest.dependencies.insert(package_name.to_string(), latest.clone());
        fs::write(&toml_path, manifest::serialize(&manifest))
            .map_err(|e| format!("Could not update kelpy.toml: {}", e))?;
    }

    Ok(format!("Installed {}@{}", package_name, latest))
}

/// Write a kelpy.lock file with pinned versions.
fn write_lock_file(project_dir: &Path, deps: &[resolver::ResolvedDep]) -> Result<(), String> {
    let lock_path = project_dir.join("kelpy.lock");
    let mut content = String::new();
    content.push_str("# KelpyShark lock file — do not edit manually\n");
    content.push_str("# Generated by kelpy install\n\n");

    for dep in deps {
        content.push_str(&format!("{} = \"{}\"\n", dep.name, dep.version));
    }

    fs::write(&lock_path, content)
        .map_err(|e| format!("Could not write kelpy.lock: {}", e))
}

/// Recursively copy a directory.
fn copy_dir_recursive(src: &Path, dest: &Path) -> Result<(), String> {
    fs::create_dir_all(dest)
        .map_err(|e| format!("Could not create '{}': {}", dest.display(), e))?;

    let entries = fs::read_dir(src)
        .map_err(|e| format!("Could not read '{}': {}", src.display(), e))?;

    for entry in entries {
        let entry = entry.map_err(|e| format!("Error: {}", e))?;
        let src_path = entry.path();
        let dest_path = dest.join(entry.file_name());

        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dest_path)?;
        } else {
            fs::copy(&src_path, &dest_path)
                .map_err(|e| format!("Could not copy '{}': {}", src_path.display(), e))?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_install_all() {
        let tmp = tempfile::tempdir().unwrap();
        let registry = Registry::new(tmp.path().join("registry"));

        // Create a library package in the registry
        let lib_dir = tmp.path().join("my_lib");
        fs::create_dir_all(lib_dir.join("src")).unwrap();
        fs::write(
            lib_dir.join("kelpy.toml"),
            "[package]\nname = \"my_lib\"\nversion = \"1.0.0\"\ndescription = \"\"\n\n[dependencies]\n",
        ).unwrap();
        fs::write(lib_dir.join("src").join("lib.ks"), "print \"lib\"").unwrap();
        registry.publish(&lib_dir).unwrap();

        // Create a project that depends on my_lib
        let proj_dir = tmp.path().join("my_project");
        fs::create_dir_all(proj_dir.join("src")).unwrap();
        fs::write(
            proj_dir.join("kelpy.toml"),
            "[package]\nname = \"my_project\"\nversion = \"0.1.0\"\ndescription = \"\"\n\n[dependencies]\nmy_lib = \"1.0.0\"\n",
        ).unwrap();

        // Install
        let result = install_all(&proj_dir, &registry);
        assert!(result.is_ok(), "Install failed: {:?}", result);

        let installed = result.unwrap();
        assert_eq!(installed.len(), 1);
        assert!(installed[0].contains("my_lib"));

        // Verify libs/ directory
        assert!(proj_dir.join("libs").join("my_lib").exists());
        assert!(proj_dir.join("libs").join("my_lib").join("kelpy.toml").exists());

        // Verify lock file
        assert!(proj_dir.join("kelpy.lock").exists());
    }

    #[test]
    fn test_install_one() {
        let tmp = tempfile::tempdir().unwrap();
        let registry = Registry::new(tmp.path().join("registry"));

        // Create lib
        let lib_dir = tmp.path().join("utils");
        fs::create_dir_all(lib_dir.join("src")).unwrap();
        fs::write(
            lib_dir.join("kelpy.toml"),
            "[package]\nname = \"utils\"\nversion = \"2.0.0\"\ndescription = \"\"\n\n[dependencies]\n",
        ).unwrap();
        fs::write(lib_dir.join("src").join("lib.ks"), "# utils").unwrap();
        registry.publish(&lib_dir).unwrap();

        // Project
        let proj_dir = tmp.path().join("proj");
        fs::create_dir_all(proj_dir.join("src")).unwrap();
        fs::write(
            proj_dir.join("kelpy.toml"),
            "[package]\nname = \"proj\"\nversion = \"0.1.0\"\ndescription = \"\"\n\n[dependencies]\n",
        ).unwrap();

        // Install one
        let result = install_one(&proj_dir, "utils", &registry);
        assert!(result.is_ok(), "Install one failed: {:?}", result);

        // Verify added to kelpy.toml
        let updated = manifest::load(&proj_dir.join("kelpy.toml")).unwrap();
        assert_eq!(updated.dependencies.get("utils"), Some(&"2.0.0".to_string()));
    }
}
